//! Cross-implementation crypto interop, driven by shared fixtures generated by the Node
//! implementation (`_fixtures/interop/`). Proves the Rust binary decrypts what `@puristic/env`
//! encrypted, and that a Node-generated keypair round-trips through the Rust encrypt/decrypt path.

use std::fs;
use std::path::PathBuf;

use puristic::crypto::decrypt::decrypt;
use puristic::crypto::encrypt::encrypt;
use puristic::crypto::format::base64url_decode;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../_fixtures/interop")
}

fn read_json(name: &str) -> serde_json::Value {
    let path = fixtures_dir().join(name);
    serde_json::from_str(&fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))).unwrap()
}

fn keypair() -> (Vec<u8>, Vec<u8>) {
    let kp = read_json("keypair.json");
    (
        base64url_decode(kp["publicKey"].as_str().unwrap()).unwrap(),
        base64url_decode(kp["privateKey"].as_str().unwrap()).unwrap(),
    )
}

#[test]
fn node_generated_keypair_has_fips203_sizes() {
    let (pk, sk) = keypair();
    assert_eq!(pk.len(), 800, "ML-KEM-512 encapsulation key");
    assert_eq!(sk.len(), 1632, "ML-KEM-512 decapsulation key");
}

#[test]
fn rust_decrypts_node_envelopes() {
    let (_pk, sk) = keypair();
    let envelopes = read_json("envelopes.json");
    let cases = envelopes.as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let plaintext = case["plaintext"].as_str().unwrap();
        let envelope = case["envelope"].as_str().unwrap();
        assert_eq!(decrypt(envelope, &sk).unwrap(), plaintext, "failed to decrypt Node envelope for {plaintext:?}");
    }
}

#[test]
fn rust_encrypt_decrypt_with_node_keypair() {
    let (pk, sk) = keypair();
    for plaintext in ["", "hello", "hełło 世界 🚀", "k=v # x"] {
        let envelope = encrypt(plaintext, &pk).unwrap();
        assert_eq!(decrypt(&envelope, &sk).unwrap(), plaintext);
    }
}
